# Generated by Django 4.2.23 on 2025-07-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_websitetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetemplate',
            name='function_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
