# Generated by Django 4.2.23 on 2025-07-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_websiteworkflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(db_column='website_id', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workflow.websiteworkflow')),
            ],
            options={
                'db_table': 'tbl_page',
            },
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_section_type',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='workflow.page')),
                ('section_type', models.ForeignKey(db_column='section_type_id', on_delete=django.db.models.deletion.CASCADE, to='workflow.sectiontype')),
            ],
            options={
                'db_table': 'tbl_section',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('html', 'HTML'), ('video', 'Video'), ('button', 'Button')], max_length=50)),
                ('content', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workflow.section')),
            ],
            options={
                'db_table': 'tbl_content_block',
            },
        ),
    ]
