# Generated by Django 4.2.23 on 2025-07-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_remove_section_config_alter_contentblock_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentblock',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
