# Generated by Django 4.2.23 on 2025-07-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_websiteworkflow_facebook_url_websiteworkflow_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteworkflow',
            name='enable_accessibility',
            field=models.IntegerField(default=0),
        ),
    ]
