# Generated by Django 4.2.23 on 2025-07-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_websiteworkflow_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteworkflow',
            name='second_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
