# Generated by Django 4.2.23 on 2025-07-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_websiteworkflow_second_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteworkflow',
            name='show_second_logo',
            field=models.IntegerField(default=0),
        ),
    ]
