# Generated by Django 4.2.23 on 2025-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_websiteworkflow_show_second_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
