# Generated by Django 4.2.23 on 2025-07-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
