# Generated by Django 4.2.23 on 2025-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_contentblock_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
