# Generated by Django 4.2.23 on 2025-07-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_contentblock_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template_path',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
