# Generated by Django 4.2.23 on 2025-07-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteworkflow',
            name='template',
            field=models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='workflow.websitetemplate'),
        ),
    ]
